### PR TITLE
GTFS import routes

### LINKED ISSUE #101: Use GTFS export for routes
@dfaulken is investigating some issues with the current export (#97 #98). I mentioned to him that another approach possibly worth considering is using the GTFS export:

- PVTA's current file: http://www.pvta.com/g_trans/ 
- Archive: https://transitfeeds.com/p/massdot/104
- Specs: https://developers.google.com/transit/gtfs/reference/

We would need to confirm with SATCo and VATCo which dates the feed files need to cover in order to include all the routes.

The upside being that we would not have to create/troubleshoot/maintain our own control file.

### PR DESCRIPTION
**Pull request by dfaulken**
Closes #101.

### CODE REVIEW

**Comment by mboneil10** [comment]
(aka I just ran it)

**Comment by werebus** [comment]
One gotcha to mention with using the GTFS routes file is that it only contains the routes that run in the time span it's exported for. So, the current one is missing routes that don't run in the summer (e.g. 38, 39, 34, 35)

**Comment by dfaulken** [comment]
@sherson didn't we assess that for this approach? Or was that when we were thinking about extracting directly from HASTUS?

**Comment by mboneil10** [comment]
huh

**Comment by sherson** [comment]
Yep https://github.com/umts/stop-project/issues/101#issuecomment-401469662

**Comment by sherson** [comment]
There were some communications elsewhere about this, but to clarify here for posterity: PVTA advised us to use the week of 2018-05-06 to 2018-06-12, which is in the archive at https://transitfeeds.com/p/massdot/104/20180501. When we do this process in the distant future, we'll need to confirm with PVTA what week we should import, and then determine if we can use the current GTFS file, or an archived one based on the calendar files. See links in first comment at #101.

**Pull request merged**
