### PR TITLE
Replace other with no sign

### LINKED ISSUE #133: Minor inconsistencies with specifications
Last inconsistencies:
- [x] `need work` has to be `needs work`.
- [x] `date stop checked by` is above stop info instead of below (as well as the time).
- [ ] `other` is a choice for `sign_type`, but it should be `no sign`.

### PR DESCRIPTION
**Pull request by dirschn**
closes #133

### CODE REVIEW

**Review by werebus — CHANGES_REQUESTED** [review]
Existing Data needs to be addressed in... some way.

Note that we _tried_ to [validate](https://github.com/umts/stop-project/blob/c721d5ebc2f9f220f13c819257cadff2bad33175/app/models/bus_stop.rb#L175-L179) that the choice is in the list. Of course, we didn't write that validation correctly so it never works...

**Comment by dirschn** [comment]
I had trouble connecting to peek the state of production data, the VPN doesn't seem to like working properly with my cell hotspot. But a janky quick local test suggests this should work assuming all the prod sign types are 'Other'.

I thought about fixing the validation, but I think that should be another PR and I dunno if I actually want to do that 😋

**Comment by dirschn** [comment]
I assume we'd want to include `nil` and `""` in the task as well then

**Comment by werebus** [comment]
No, blank values are allowed (for "incomplete" stops).

**Review by werebus — APPROVED** [review]

**Pull request merged**
