### PR TITLE
Broken migrations

### PR DESCRIPTION
**Pull request by mboneil10**
Didn't need to make new migration for creating fields -- it's already [there](https://github.com/umts/stop-project/blob/rewrite/db/migrate/20180614232652_create_fields.rb)

### CODE REVIEW

**Comment by mboneil10** [comment]
https://github.com/umts/stop-project/blob/rewrite/db/migrate/20180614232652_create_fields.rb

**Comment by mboneil10** [comment]
uhhhh

**Comment by jforgue** [comment]
So we don't want to drop the `fields` table?

**Comment by mboneil10** [comment]
```ActiveRecord::HasManyThroughOrderError in BusStops#manage
Showing /Users/molly/stop-project/app/views/bus_stops/manage.haml where line #16 raised:

Cannot have a has_many :through association 'BusStop#routes' which goes through 'BusStop#bus_stops_routes' before the through association is defined.
```

**Comment by mboneil10** [comment]
@jforgue don't think so

**Comment by jforgue** [comment]
If I understand correctly, somehow the `fields` table didn't exist before theses migrations?

**Comment by mboneil10** [comment]
Yes, the `fields` table didn't exist before the two deleted migrations.

**Comment by mboneil10** [comment]
I'm going to look into this association problem before this gets merged.

**Comment by mboneil10** [comment]
Why would this association problem happen NOW. wtf

**Comment by mboneil10** [comment]
Closing for now so no one accidentally merges. Need to figure out the association problem

**Pull request closed without merging**
