### PR TITLE
Merge rewrite and master

### PR DESCRIPTION
**Pull request by mboneil10**
Perhaps this PR is really dumb. But I want to make sure that what we want in the rewrite is there, and nothing "super important" will disappear.

### CODE REVIEW

**Comment by mboneil10** [comment]
And idk why I can't migrate anymore. So much confusion.

**Comment by dfaulken** [comment]
We don't want to merge yet, right? Still some TODOs?

This is just for review?

**Comment by mboneil10** [comment]
Oh shit I misinterpreted the conversation on slack. I wanted to pull `master` into `rewrite`. I might have done the wrong thing? I'll delete the branch

**Comment by mboneil10** [comment]
Did it the wrong way :P

**Pull request closed without merging**
